# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_PID')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_PID')
    _PID = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PID', [dirname(__file__)])
        except ImportError:
            import _PID
            return _PID
        try:
            _mod = imp.load_module('_PID', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _PID = swig_import_helper()
    del swig_import_helper
else:
    import _PID
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class PID(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PID, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PID, name)
    __repr__ = _swig_repr
    __swig_setmethods__["P"] = _PID.PID_P_set
    __swig_getmethods__["P"] = _PID.PID_P_get
    if _newclass:
        P = _swig_property(_PID.PID_P_get, _PID.PID_P_set)
    __swig_setmethods__["I"] = _PID.PID_I_set
    __swig_getmethods__["I"] = _PID.PID_I_get
    if _newclass:
        I = _swig_property(_PID.PID_I_get, _PID.PID_I_set)
    __swig_setmethods__["D"] = _PID.PID_D_set
    __swig_getmethods__["D"] = _PID.PID_D_get
    if _newclass:
        D = _swig_property(_PID.PID_D_get, _PID.PID_D_set)
    __swig_setmethods__["iAccumulator"] = _PID.PID_iAccumulator_set
    __swig_getmethods__["iAccumulator"] = _PID.PID_iAccumulator_get
    if _newclass:
        iAccumulator = _swig_property(_PID.PID_iAccumulator_get, _PID.PID_iAccumulator_set)
    __swig_setmethods__["prevError"] = _PID.PID_prevError_set
    __swig_getmethods__["prevError"] = _PID.PID_prevError_get
    if _newclass:
        prevError = _swig_property(_PID.PID_prevError_get, _PID.PID_prevError_set)
    __swig_setmethods__["debug"] = _PID.PID_debug_set
    __swig_getmethods__["debug"] = _PID.PID_debug_get
    if _newclass:
        debug = _swig_property(_PID.PID_debug_get, _PID.PID_debug_set)
    __swig_setmethods__["first"] = _PID.PID_first_set
    __swig_getmethods__["first"] = _PID.PID_first_get
    if _newclass:
        first = _swig_property(_PID.PID_first_get, _PID.PID_first_set)
    __swig_setmethods__["file"] = _PID.PID_file_set
    __swig_getmethods__["file"] = _PID.PID_file_get
    if _newclass:
        file = _swig_property(_PID.PID_file_get, _PID.PID_file_set)
    __swig_setmethods__["sTime"] = _PID.PID_sTime_set
    __swig_getmethods__["sTime"] = _PID.PID_sTime_get
    if _newclass:
        sTime = _swig_property(_PID.PID_sTime_get, _PID.PID_sTime_set)

    def __init__(self, *args):
        this = _PID.new_PID(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def update(self, target: 'double', current: 'double') -> "double":
        return _PID.PID_update(self, target, current)

    def reset(self) -> "void":
        return _PID.PID_reset(self)

    def close(self) -> "void":
        return _PID.PID_close(self)
    __swig_destroy__ = _PID.delete_PID
    __del__ = lambda self: None
PID_swigregister = _PID.PID_swigregister
PID_swigregister(PID)

# This file is compatible with both classic and new-style classes.


